opt_in_rules:
  - empty_count

included:
  - ../../Sources

analyzer_rules:
  - explicit_self

force_cast: warning
force_try:
  severity: warning

line_length:
  warning: 160
  error: 240
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
identifier_name:
  min_length:
    error: 3
  excluded:
    - se
    - no
    - id
    - URL
