language: objective-c
osx_image: xcode12.2
cache:
  - bundler

env:
  global:
    # GH_TOKEN
    - secure: "VZNpEJSqhtjbzVwWKk3xSFgpD7EkqgxXQlqeK0fB+6DYCdAOtp2wzlZ2jvRJ3oMpZFfS9H8mll95QGmMopMJYQ2griEcrUf2CcSILDCSF9sOykn7gDFStHSXNDX42IsQzBBhmSEaT8HqpKwC57IbP4OCbDzGhU04csv9E+LH2A/bwRowzjB5uzhzBoRtdxL/7phNlbTdPRzwU+8166p46cB14kbEakAZEvZ9i6pXR7t0t2EGerPgpwsvGNbXxipNdbIBebksvMhO88M8NcyHrm8HXckGH79xgpOrUyHn3BnjisfZsZP9kAEuwCzENMGQDQm5TE9YZFz9ZfHD3mCsnGEDxotHJms8dadptNjSxK8WA+r2sz/UbT5EizGh6qZjtfBcjGQq3RCsm/eqackQ/XAk7RcihSXiGpdukNjaRZZDfm2x84Eb0CMPL7s/XnJgmM+5Ar2o1icGY6dQGv35nULOlsKkI126AJ3IMy+QjePgAU7j4STuBAVljHJWoPfzjwfDHPDc0qGCkEC2/6eEszR/YWgXGR/7poWNJJcsBW/jdXhXKunAjG/tpwtwTv6yVWvBcXKUrrFlXtP4Zs6r0yoQ+FeX/rxFrmYzkng62QPMY8R2EnwijPKhHgPHkchFuUQBR8kJcRMEXvwun6SP4bD0KtEHKnxfG3/sC5/CMu0="


xcode_project: Projects/AccountSDKIOSWeb/AccountSDKIOSWeb.xcodeproj
xcode_destination: platform=iOS Simulator,OS=14.2,name=iPhone 12
xcode_scheme: AccountSDKIOSWebTests

before_script: xcodebuild -resolvePackageDependencies -project Projects/AccountSDKIOSWeb/AccountSDKIOSWeb.xcodeproj build

before_deploy:
 - bundle install
 - bundle exec jazzy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  verbose: true
  local_dir: docs
  on:
    repo: schibsted/AccountSDKIOSWeb
    branch: master
