language: swift
osx_image: xcode12.2

xcode_project: AccountSDKIOSWeb.xcodeproj
xcode_destination: platform=iOS Simulator,OS=11.0,name=name=iPhone X

matrix:
 - xcode_scheme: AccountSDKIOSWebTests
 - xcode_scheme: AccountSDKIOSKeychainTests

