language: swift
osx_image: xcode12.2

xcode_project: AccountSDKIOSWeb.xcodeproj
xcode_destination: platform=iOS Simulator,OS=14.2,name=name=iPhone X
xcode_scheme:
  - AccountSDKIOSWebTests
  - AccountSDKIOSWebKeychainTests
