name: build

on:
  pull_request:
  push:
    branches:
     - master

env:
  platform: 'iOS Simulator'
  iOS: '17.0.1'
  device: 'iPhone 15'

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Resolve package dependencies
        run: |
          xcodebuild -resolvePackageDependencies -project Projects/AccountSDKIOSWeb/AccountSDKIOSWeb.xcodeproj
      - name: Build the SDK
        run: |
          xcodebuild build -project Projects/AccountSDKIOSWeb/AccountSDKIOSWeb.xcodeproj -scheme AccountSDKIOSWeb -destination "platform=$platform,name=$device,OS=$iOS"

      - name: Build for testing
        run: |
          xcodebuild build-for-testing -project Projects/AccountSDKIOSWeb/AccountSDKIOSWeb.xcodeproj -scheme AccountSDKIOSWebTests -destination "platform=$platform,name=$device,OS=$iOS"

      - name: Run unit tests
        run: |
          xcodebuild test-without-building -project Projects/AccountSDKIOSWeb/AccountSDKIOSWeb.xcodeproj -scheme AccountSDKIOSWebTests -destination "platform=$platform,name=$device,OS=$iOS"
