name: Build the Account SDK and the Example app

on:
  pull_request:
  push:
    branches:
     - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Resolve package dependencies
        run: |
          xcodebuild -resolvePackageDependencies -project Projects/AccountSDKIOSWeb/AccountSDKIOSWeb.xcodeproj
      - name: Build the SDK
        env:
          platform: ${{ 'iOS Simulator' }}
        run: |
          xcodebuild build -project Projects/AccountSDKIOSWeb/AccountSDKIOSWeb.xcodeproj -scheme AccountSDKIOSWeb -destination "platform=$platform"
      - name: Run unit tests
        env:
          platform: ${{ 'iOS Simulator' }}
          iOS: ${{ '15.6' }}
          device: ${{ 'iPhone 13' }}
        run: |
          xcodebuild test -project Projects/AccountSDKIOSWeb/AccountSDKIOSWeb.xcodeproj -scheme AccountSDKIOSWebTests -destination "platform=$platform,name=$device,OS=$iOS"
